//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoDuong1
    {
        public int IDBaoDuong { get; set; }
        public int MaDL { get; set; }
        public int IDVatTu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> IDTienCong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DATLICH DATLICH { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
