//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBD
    {
        public int IDChiTietBD { get; set; }
        public Nullable<int> MaDL { get; set; }
        public Nullable<int> IDKM { get; set; }
        public Nullable<int> IDVatTu { get; set; }
    
        public virtual DATLICH DATLICH { get; set; }
        public virtual SOKM SOKM { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
