//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietUser()
        {
            this.NhanCongSuaChuaXes = new HashSet<NhanCongSuaChuaXe>();
            this.NhapKhoes = new HashSet<NhapKho>();
            this.PhanQuyens = new HashSet<PhanQuyen>();
            this.TiepNhanXes = new HashSet<TiepNhanXe>();
        }
    
        public int IDNguoiDung { get; set; }
        public int IDChucVu { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> Luong { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Anh { get; set; }
        public string tk { get; set; }
        public string mk { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanCongSuaChuaXe> NhanCongSuaChuaXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapKho> NhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiepNhanXe> TiepNhanXes { get; set; }
    }
}
