//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATLICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATLICH()
        {
            this.BaoDuong1 = new HashSet<BaoDuong1>();
            this.ChiTietBDs = new HashSet<ChiTietBD>();
        }
    
        public int MaDL { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<int> IDTiepNhanXe { get; set; }
        public Nullable<int> IDTienCong { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoDuong1> BaoDuong1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBD> ChiTietBDs { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual TiepNhanXe TiepNhanXe { get; set; }
    }
}
