//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int IDUser { get; set; }
        public int IDQuyen { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChiTietUser ChiTietUser { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
