//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThayVatTu
    {
        public int IDThayVatTu { get; set; }
        public Nullable<int> IDVatTu { get; set; }
        public Nullable<int> IDSuaChua { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> IDDichVu { get; set; }
        public Nullable<System.DateTime> NgayThay { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual SuaChua SuaChua { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
