//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiepNhanXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiepNhanXe()
        {
            this.DATLICHes = new HashSet<DATLICH>();
            this.SuaChuas = new HashSet<SuaChua>();
        }
    
        public int IDTiepNhanXe { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<System.DateTime> NgayTiepNhan { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public Nullable<int> IDThuongHieuXe { get; set; }
        public Nullable<bool> BanGiaoXe { get; set; }
        public Nullable<int> IDNhanVien { get; set; }
    
        public virtual ChiTietUser ChiTietUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATLICH> DATLICHes { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuaChua> SuaChuas { get; set; }
        public virtual ThuongHieuXe ThuongHieuXe { get; set; }
    }
}
