//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VatTu()
        {
            this.BaoDuong1 = new HashSet<BaoDuong1>();
            this.ChiTietBDs = new HashSet<ChiTietBD>();
            this.CTNhapKhoVTs = new HashSet<CTNhapKhoVT>();
            this.CTTonKhoes = new HashSet<CTTonKho>();
            this.ThayVatTus = new HashSet<ThayVatTu>();
            this.ThongKeVts = new HashSet<ThongKeVt>();
        }
    
        public int IDVatTu { get; set; }
        public string Ten { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Anh { get; set; }
        public Nullable<int> IDHangXe { get; set; }
        public Nullable<int> IDLoai { get; set; }
        public Nullable<int> GiaNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoDuong1> BaoDuong1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBD> ChiTietBDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNhapKhoVT> CTNhapKhoVTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTonKho> CTTonKhoes { get; set; }
        public virtual LoaiVatTu LoaiVatTu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThayVatTu> ThayVatTus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKeVt> ThongKeVts { get; set; }
        public virtual ThuongHieuXe ThuongHieuXe { get; set; }
    }
}
